### ISSUE TITLE
[FEATURE] Let AutocompleteInput accept input not present in completion list

### ISSUE THREAD

**Issue by ltalirz** [bokeh/bokeh#10295]
**Is your feature request related to a problem? Please describe.**
One of the main purposes of the `AutocompleteInput` widget is to select a value from a long list (for short lists, one could use `Select`). However, lists tend to become long when people keep adding to them.

Currently, `AutocompleteInput` forces users to choose one of the items from the list of completions, thus excluding users from the process of building the list.

**Describe the solution you'd like**
It would be nice, if users could input values that are not yet in the `completions`.
This has been requested & upvoted on the `panel` repo: https://github.com/holoviz/panel/issues/685 as well as here  https://github.com/bokeh/bokeh/issues/9605#issuecomment-578399191 

Essentially, we are looking for the behavior of dash's `dcc.Input` widget with the `list` field https://dash.plotly.com/dash-core-components/input

**Additional context**
When I read the name `AutocompleteInput`, it actually makes me assume that users can enter their own values (as is usually the case with an `Input`). However, this would require a change in the docs, as the current implementation is essentially using an `Input` to `Select` from a fixed list.

@bryevdv Before starting to look into the code, it would be good to know whether you would consider adding a switch to enable this functionality in the `AutocompleteInput` widget or whether you think this should be added in a different one.

**Comment by bryevdv** [comment]
@ltalirz I don't have strong feelings here. Definitely when creating `AutoComplete` we had in mind the case where the list of acceptable inputs is fixed by the developer (e.g. a list of US state names, or all your business's current vendors, etc). That said I can imagine there are cases that involve more open-ended input but would also like an auto-complete as a suggestive aid. 

@bokeh/dev anyone have firm opinions about this, new configuration on `AutoComplete` vs new widget? I suppose my slight bias is to avoid new widgets unless really necessary.

**Comment by p-himik** [comment]
I agree that a new widget is unnecessary. In fact, I've dealt with autocomplete widgets in other libraries, and I don't recall ever coming across a separate widget specifically for mere suggestions and not fixed items. Usually it is indeed just a boolean flag.

**Comment by jbednar** [comment]
Boolean flag makes sense to me, as most people need never worry about this issue, and will discover it by trying the existing widget and realizing that they want to change this behavior, in which case they can discover the flag.

**Comment by bryevdv** [comment]
seems we are fairly well aligned, for ref the relevant BokehJS code is here:

https://github.com/bokeh/bokeh/blob/branch-2.2/bokehjs/src/lib/models/widgets/autocomplete_input.ts
