### ISSUE TITLE
[BUG] sizing_mode='stretch_both' broken in gridplot (bokeh 3.0.2)

### ISSUE THREAD

**Issue by jnettels** [bokeh/bokeh#12614]
### Software versions

Python version      :  3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.2
BokehJS static path :  C:\Users\***\anaconda3\envs\bokeh3\Lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22000-SP0

### Browser name and version

Chrome, Firefox, Edge

### Expected behavior

Plots arranged in a gridplot are not shown correctly, when compared to bokeh 2.4.3

I simplified this example:
https://docs.bokeh.org/en/3.0.2/docs/examples/basic/data/color_mappers.html

With bokeh 2.4.3 it shows 4 plots that stretch to the edges of the browser.

### Observed behavior

With bokeh 3.0.1 and 3.0.2 the plot is messed up. The toolbar is in the correct place, but apart from some fragments of the axis, the plots are too small to be visible. They appear compressed to 0 width and height in the top left corner.

### Example code

```Python
import numpy as np

from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show

x = np.random.random(size=2000) * 1000
y = np.random.normal(size=2000) * 2 + 5
source = ColumnDataSource(dict(x=x, y=y))

def make_plot(mapper_type, palette):
    p = figure(x_range=(1, 1000), title=f"{palette} with {mapper_type} mapping",
               x_axis_type=mapper_type)
    p.scatter('x', 'y', alpha=0.8, source=source)
    return p

p1 = make_plot("linear", "Viridis256")
p2 = make_plot("log", "Viridis256")
p3 = make_plot("linear", "Viridis6")
p4 = make_plot("log", "Viridis6")

grid =  gridplot([[p1, p2], [p3, p4]],
                sizing_mode='stretch_both',
                 # width=400, height=300,
                 # toolbar_location=None,
                 )
show(grid)
```

### Stack traceback or browser console output

browser console does not seem to show errors

### Screenshots

![image](https://user-images.githubusercontent.com/8526498/201964771-e583d509-3ad7-49a4-bc6d-7b85fda8efb6.png)

**Comment by yinyea** [comment]
"sizing_mode='stretch_both' broken in gridplot", is this bug solved? seems merged with other issues but cannot find any update..

**Comment by bryevdv** [comment]
It is fixed on current latest `branch-3.1` which is not yet released.

**Comment by philippjfr** [comment]
This seems like the same issue as https://github.com/bokeh/bokeh/issues/12863 which does not appear to be fixed yet.

**Comment by bryevdv** [comment]
You are correct, *will be* fixed on `branch-3.1`. I was impatient and investigating status on my phone and misinterpreted something.

**Comment by lmezg** [comment]
hi @bryevdv, I'm currently using 3.1.1, but I still see this issue with stretch_both, I guess the fix is not released ?

**Comment by bryevdv** [comment]
@gengjun The fix for this issue is released, and I just double checked that the code in the OP above is working as expected with Bokeh 3.1.1. If you are seeing a problem, it is something else, even though it may seem similar. Please open a new issue with complete details. 

<img width="1521" alt="Screenshot 2023-05-16 at 15 06 41" src="https://github.com/bokeh/bokeh/assets/1078448/fab7dcb1-0147-402a-9173-0399b6a530b0">

**Comment by lmezg** [comment]
@bryevdv , It's odd, for this example, if I simply add sizing_mode="stretch_both" to gridplot() function call, the first four plots vanished. (I also noticed that this example is not using sizing_mode at all :-)) 
https://docs.bokeh.org/en/3.1.1/docs/examples/basic/data/color_mappers.html
![image](https://github.com/bokeh/bokeh/assets/4976364/a829bf24-c053-4f60-b4c5-c852b17b27a3)

**Comment by bryevdv** [comment]
@gengjun 

> Please open a new issue with complete details.
