### ISSUE TITLE
(0.9.3) BokehJS not loading in IPython Notebook

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2709]
Here's a bug that's a little frustrating. `bokeh.js` works fine in an html file, but breaks in an IPython Notebook, first noticed by @birdsarah 

```python
In [1]: from IPython.display import HTML, Javascript, display

In [2]: %%html
         <script src="bokehjs/build/js/bokeh.js"></script>

In [3]: %%javascript
         console.log(Bokeh);

    #=> Javascript error adding output!
    #=> ReferenceError: Bokeh is not defined
    #=> See your browser Javascript console for more details.
```
I have not yet been able to pin down the exact reason for the difference in behavior. I have observed, in the compiled `bokeh.js`, that in modules that `require("backbone")`
```
.
.
.
},{"./continuum_view":39,"underscore":23}],38:[function(require,module,exports){
var Backbone, Collection,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Backbone = require("backbone");

Collection = (function(superClass) {
  extend(Collection, superClass);

  function Collection() {
    return Collection.__super__.constructor.apply(this, arguments);
  }

  return Collection;

})(Backbone.Collection);

module.exports = Collection;
.
.
.
```
`Backbone` is being set as an empty `{}`, which is the cause for the error being thrown. `require("underscore")`, etc. seem to work fine.

**Comment by damianavila** [comment]
I found the notebook working before this PR: https://github.com/bokeh/bokeh/pull/2706
Can somebody else check if that the case for you as well?

**Comment by damianavila** [comment]
I linked the wrong PR in the previous answer, it is #2671, as I corrected above... thanks.

**Comment by mistakevin** [comment]
I have figured it out. Working on a PR now

**Comment by mistakevin** [comment]
Tipping my hat to this [SO](http://stackoverflow.com/questions/25999947/how-to-solve-a-conflict-between-browserify-backbone-based-app-and-require-js-o) :tophat: for understanding the issue.

**Comment by arjan-hada** [comment]
Can anyone please explain to me how was this issue resolved? I am still facing the issue. Your help means a lot to me.

**Comment by bryevdv** [comment]
@arjan-hada there have been no reported problems for a long time. If you are experiencing problems then it is almost certainly something new or different. Please make a new GitHub issue with *complete an detailed information* including all conda or pip environment package versions, system/os information and a complete minimal notebook that reproduces the problem.
