### ISSUE TITLE
bokeh.js must load first, before widgets, compiler

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3500]
refererence: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/aJPeJUottKk

ping @mattpap 

Any immediate thoughts? There are definitely ways to chain callbacks together to load one first. We'd have to special case the first to be the "load first" script, or else chain them all together in order in general. Or we could put a fixed number of timeout retries when `Bokeh` is not found as a stopgap.

**Comment by bryevdv** [comment]
OK the following patch seems to work, maybe there is a way to improve it in the short term? Long term I guess we should be using `require`?

```
diff --git a/bokeh/core/_templates/js_resources.html b/bokeh/core/_templates/js_resources.html
index 014740d..6a02ca4 100644
--- a/bokeh/core/_templates/js_resources.html
+++ b/bokeh/core/_templates/js_resources.html
@@ -9,9 +9,40 @@ configuration in a Resources object.
 :type js_raw: list[str]
 
 #}
-{%- for file in js_files %}
-<script type="text/javascript" src="{{ file }}"></script>
-{%- endfor %}
+<script type="text/javascript">
+    function loadScript(url, callback) {
+
+        var script = document.createElement("script")
+        script.type = "text/javascript";
+
+        if (script.readyState){  //IE
+            script.onreadystatechange = function(){
+                if (script.readyState == "loaded" ||
+                        script.readyState == "complete"){
+                    script.onreadystatechange = null;
+                    callback();
+                }
+            };
+        } else {  //Others
+            script.onload = function(){
+                console.log(url, "LOADED")
+                callback();
+            };
+        }
+
+        script.src = url;
+        document.getElementsByTagName("head")[0].appendChild(script);
+    }
+
+    {%- if js_files|length > 0 %}
+    loadScript("{{ js_files[0] }}", function(){
+        {%- for file in js_files[1:] %}
+        loadScript("{{ file }}", function(){});
+        {%- endfor %}
+    });
+   {% endif %}
+
+</script>
 
 {%- for js in js_raw %}
 <script type="text/javascript">
```

**Comment by bryevdv** [comment]
Well I spoke too soon that does not seem to solve the problem, at least not entirely. It's still possible to see the `ReferenceError: Can't find variable: Bokeh`

**Comment by bryevdv** [comment]
Well it appears to be complaining on reloads because `Bokeh.set_log_level` is happening to early.

**Comment by bryevdv** [comment]
This patch is slighty "better" in that I think renderered `output_notebook` cells will always work, but it's still possible for notebooks to get to `show` too early 

```
iff --git a/bokeh/core/_templates/js_resources.html b/bokeh/core/_templates/js_resources.html
index 014740d..af81c46 100644
--- a/bokeh/core/_templates/js_resources.html
+++ b/bokeh/core/_templates/js_resources.html
@@ -9,12 +9,48 @@ configuration in a Resources object.
 :type js_raw: list[str]
 
 #}
-{%- for file in js_files %}
-<script type="text/javascript" src="{{ file }}"></script>
-{%- endfor %}
+<script type="text/javascript">
+    function loadScript(url, callback) {
+
+        var script = document.createElement("script")
+        script.type = "text/javascript";
+
+        if (script.readyState){  //IE
+            script.onreadystatechange = function(){
+                if (script.readyState == "loaded" ||
+                        script.readyState == "complete"){
+                    script.onreadystatechange = null;
+                    callback();
+                }
+            };
+        } else {  //Others
+            script.onload = function(){
+                console.log(url, "LOADED")
+                callback();
+            };
+        }
+
+        script.src = url;
+        document.getElementsByTagName("head")[0].appendChild(script);
+    }
+
+    {%- if js_files|length > 0 %}
+    loadScript("{{ js_files[0] }}", function(){
+        {%- for file in js_files[1:] %}
+        loadScript("{{ file }}", function(){});
+        {%- endfor %}
+        {%- for js in js_raw %}
+            {{ js|indent(4) }}
+        {% endfor %}
+    });
+   {% endif %}
+
+</script>
 
+{%- if js_files|length == 0 %}
 {%- for js in js_raw %}
 <script type="text/javascript">
     {{ js|indent(8) }}
 </script>
 {%- endfor %}
+{% endif %}

```

**Comment by bryevdv** [comment]
Another option of course is to restore `INLINE` resources as the default.

ping @bokeh/core for ideas

**Comment by havocp** [comment]
Does it fix it to just add async=false on the script tags?

We had this exact problem a while back (except outside of notebook, I think in autoload?) and talked about various solutions on a past PR; one helpful thing we did then was set async=false on the script tag. But we can probably use the exact same library loading code in both places ... https://github.com/bokeh/bokeh/blob/master/bokeh/core/_templates/autoload_js.js
If we want the dynamically added script tag we should probably try to share that code... unless it's different in a subtle way ?

**Comment by bryevdv** [comment]
just `async="false"` does not seem to work

**Comment by bryevdv** [comment]
Agreed should find a way to re-use autoload loading code, I will look into that.

**Comment by mattpap** [comment]
@bryevdv, I will investigate this today.

**Comment by bryevdv** [comment]
Thanks @mattpap please keep me up to date as much as you can.

**Comment by bryevdv** [comment]
@mattpap can you update? (any help needed or questions)? My plan had been to cut an RC1 early tomorrow morning CST, I need to know if we might need to plan for a contingency.

**Comment by mattpap** [comment]
@bryevdv, still investigating.

**Comment by havocp** [comment]
I think the problem may be that we no longer set window.Bokeh:
https://github.com/bokeh/bokeh/commit/d2e678338b0e0f04b0b3b5dcdc92db870a03f75a#diff-4857f50760cfb358c5b6cbcb34633cdfL125

```
diff --git a/bokehjs/src/coffee/main.coffee b/bokehjs/src/coffee/main.coffee
index a0b8f08..0cbdb81 100644
--- a/bokehjs/src/coffee/main.coffee
+++ b/bokehjs/src/coffee/main.coffee
@@ -33,3 +33,7 @@ require("./api/plugin")
 # Here for backwards capability?
 Bokeh.Bokeh = Bokeh
 module.exports = Bokeh
+
+# this is needed in notebooks because we aren't loaded
+# with the window as our scope
+window.Bokeh = Bokeh
```

However it's a little hard to test since I can't just put it on the cdn ;-)

**Comment by bryevdv** [comment]
well it's easy to make a new dev build to try this while @mattpap looks into other things.

**Comment by havocp** [comment]
It may be this should be fixed at the top of bokeh.js, where it has `Bokeh = # stuff from prelude.js`, that's the thing that I guess doesn't work... maybe we should do `window.Bokeh =` here, or maybe the issue is that the prelude.js function doesn't return the right value, I'm not sure.
I don't think my diff above is really the right fix. @mattpap will know the better way.

**Comment by havocp** [comment]
I made a PR but I'm not sure my theory makes that much sense to me; even if the scope here is something weird, why don't the three bokeh scripts share the same scope?

**Comment by mattpap** [comment]
> why don't the three bokeh scripts share the same scope?

Can you elaborate? Currently they share a global variable `Bokeh`.

> However it's a little hard to test since I can't just put it on the cdn ;-)

@havocp, you can use local bokeh server as a CDN. Just change resources in a notebook to `server`. You could even use `server-dev` resources, if it only worked.

**Comment by mattpap** [comment]
Can someone tell me how to disable automatic evaluation in jupyter notebook? This new "feature" drives me nuts. @damianavila?

**Comment by mattpap** [comment]
No progress today. @havocp's solution helps, but doesn't resolve the underlying issue.

**Comment by bryevdv** [comment]
@mattpap what about cleaning up a simple load ordering solution for the immediate time being?

**Comment by mattpap** [comment]
@bryevdv, you mean proceeding with #3501? If it works, then sure. However, I will continue attempt to understand what is going on here, because the existing code should work.

**Comment by havocp** [comment]
for me everything appeared to load in the right order, it's just that the Bokeh var was never defined.

**Comment by havocp** [comment]
ok I was totally confused before, ignore the window.Bokeh thing and the rest.

async="false" was nonsense because you can't set it false in HTML. In JavaScript you can do `domNode.async=false`, but in HTML there's no way to set it to false (setting it to anything, including `"false"`, makes it true).  In a static HTML page the script tag defaults to async false, but for dynamically-added script tags, async apparently defaults to true (for most browsers anyway). Discussion here for example: http://stackoverflow.com/questions/3408805/is-the-async-attribute-property-useful-if-a-script-is-dynamically-added-to-the

Anyhow, I didn't go test a bunch of browsers, but chrome is indeed loading bokeh.js after bokeh-widgets.js and bokeh-compiler.js for me, and that appears to be the problem... because the script tags are added dynamically they are always async unless we set async=false from code.

**Comment by havocp** [comment]
So my current theory is: the reason notebook breaks is that it adds `js_resources.html` (our several script tags) dynamically, which causes them to load async (script tags default to async when loaded dynamically). `file.html` works fine in a non-notebook context because when the script tags are in the page to start with instead of added dynamically, they default to async=false. And autoload works fine outside of notebook because in `autoload_js.js` we create the script tag in JS and set `node.async=false` from the JS, thus forcing the scripts to load in order.

I think notebook_load.html and notebook_div.html may be about exactly analogous to the two halves of autoload_js.js (the two halves are the load_libs function and the stuff after it). It should be possible for all of this to work in a consistent way across the different contexts... probably by always working the autoload.js way, more or less.

**Comment by mattpap** [comment]
This is my observation as well. It was a little surprising to me to learn that scripts can be loaded synchronously or asynchronously depending on context (well, web dev is a mess, so it's not that much surprising). As I view it currently, bokeh and notebook never really worked properly, only by mere coincidence that `load_notebook()` and `notebook_div()` happened in different cells, so there was just enough time for bokeh to load. Adding widgets and compiler bundles just exaggerates the issue, as well as notebook adding automatic evaluation. So I think we should proceed, as @havocp suggested, with autoload. I would be tempted to use `async=false` (by injecting inline scripts that add remote scripts), but that will most likely not work in IE (maybe besides the most recent one).

**Comment by bryevdv** [comment]
@mattpap do you think you can implement something today?

**Comment by mattpap** [comment]
@bryevdv, yes, just reimplemented `autoload_static()` to accept raw javascript and heading towards making this usable from notebook.
