### ISSUE TITLE
Bokeh 0.11 monstrously slow as compared to 0.10.

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#3617]
I have a script that produces Bokeh plots via the CDN, and this script runs quickly in Python 2.7, but since migrating to 3.5.1 it is *ultra* slow (30 seconds per plot vs. a fraction of a second previously!). The speed difference is about factor of 100 or more. Not sure what to try, had freshly install Python 3.5.1 and Bokeh. Any thoughts as to the cause?

**Comment by guillochon** [comment]
I should also mention that I was using Bokeh 0.10 with Python 2.7, 0.10 would not work at all with 3.5 so I was forced to use 0.11.

**Comment by bryevdv** [comment]
Sounds like a bug, or possibly a bad usage that should be made more difficult to do. Unfortunately without some kind of example code that reproduces the problem there's nothing to even speculate about. If you can provide more to go on we can try to investigate.

**Comment by guillochon** [comment]
Hi bryevdv, below is the code snippet that generates the plots. It is within a loop that runs a few thousand times, and it does seem like the plotting becomes slower the more iterations through the loop, so I'm thinking it could be some sort of leak. I commented out many of the intermediate lines (replacing them with small dummy datasets) and it was still very slow.

Anyway, let me know if you have any ideas. The code still works wonderfully in 2.7, but I was hoping to transition my stuff to 3.5 since that's "the future of Python."

```Python
    if plotavail:
        phototime = [float(catalog[entry]['photometry'][x]['time']) for x in prange]
        photoAB = [float(catalog[entry]['photometry'][x]['abmag']) for x in prange]
        photoerrs = [float(catalog[entry]['photometry'][x]['aberr']) if 'aberr' in catalog[entry]['photometry'][x] else 0. for x in prange]

        x_buffer = 0.1*(max(phototime) - min(phototime)) if len(phototime) > 1 else 1.0
        x_range = [-x_buffer + min(phototime), x_buffer + max(phototime)]

        p1 = figure(title='Photometry for ' + eventname, x_axis_label='Time (' + catalog[entry]['photometry'][0]['timeunit'] + ')',
            y_axis_label='AB Magnitude', x_range = x_range, tools = tools,
            y_range = (0.5 + max([x + y for x, y in list(zip(photoAB, photoerrs))]), -0.5 + min([x - y for x, y in list(zip(photoAB, photoerrs))])))
        p1.add_tools(hover)

        err_xs = []
        err_ys = []

        for x, y, yerr in list(zip(phototime, photoAB, photoerrs)):
            err_xs.append((x, x))
            err_ys.append((y - yerr, y + yerr))

        photoband = [catalog[entry]['photometry'][x]['band'] for x in prange]
        photoinstru = [catalog[entry]['photometry'][x]['instrument'] if 'instrument' in catalog[entry]['photometry'][x] else '' for x in prange]
        photosource = [', '.join(str(j) for j in sorted(int(i) for i in catalog[entry]['photometry'][x]['source'].split(','))) for x in prange]
        phototype = [bool(catalog[entry]['photometry'][x]['upperlimit']) if 'upperlimit' in catalog[entry]['photometry'][x] else False for x in prange]
        bandset = set(photoband)
        bandset = [i for (j, i) in sorted(list(zip(list(map(bandaliasf, bandset)), bandset)))]

        for band in bandset:
            bandname = bandaliasf(band)
            indb = [i for i, j in enumerate(photoband) if j == band]
            indt = [i for i, j in enumerate(phototype) if j == 0]
            ind = set(indb).intersection(indt)

            source = ColumnDataSource(
                data = dict(
                    x = [phototime[i] for i in ind],
                    y = [photoAB[i] for i in ind],
                    err = [photoerrs[i] for i in ind],
                    desc = [photoband[i] for i in ind],
                    instr = [photoinstru[i] for i in ind],
                    src = [photosource[i] for i in ind]
                )
            )
            p1.circle('x', 'y', source = source, color=bandcolorf(band), legend=bandname, size=4)
            p1.multi_line([err_xs[x] for x in ind], [err_ys[x] for x in ind], color=bandcolorf(band))

            upplimlegend = bandname if len(ind) == 0 else ''

            indt = [i for i, j in enumerate(phototype) if j == 1]
            ind = set(indb).intersection(indt)
            p1.inverted_triangle([phototime[x] for x in ind], [photoAB[x] for x in ind],
                color=bandcolorf(band), legend=upplimlegend, size=7)

        p = p1

        #save(p)
        html = file_html(p, CDN, eventname)
        returnlink = r'    <a href="https://sne.space"><< Return to supernova catalog</a>';
        #html = re.sub(r'(\<body\>)', r'\1\n    '+returnlink, html)
        html = re.sub(r'(\<\/body\>)', r'    <a href="data/' + eventname + r'.json.bz2">Download datafile</a><br><br>\n        \1', html)
        if len(catalog[entry]['sources']):
            html = re.sub(r'(\<\/body\>)', r'<em>Sources of data:</em><br><table><tr><th>ID</th><th>Source</th></tr>\n        \1', html)
            for source in catalog[entry]['sources']:
                html = re.sub(r'(\<\/body\>)', r'<tr><td>' + source['alias'] + r'</td><td>'+source['name'].encode('ascii', 'xmlcharrefreplace')+r'</td></tr>\n        \1', html)
            html = re.sub(r'(\<\/body\>)', r'</table>\n    \1', html)
        html = re.sub(r'(\<\/body\>)', returnlink+r'\n    \1', html)
        print(outdir + eventname + ".html")
        with open(outdir + eventname + ".html", "w") as f:
            f.write(html)
```

**Comment by guillochon** [comment]
One more thing: It did seem like the element calls, like `p1.circle`, `p1.multi_line`, were particularly slow.

**Comment by guillochon** [comment]
Ah hah, it is Bokeh 0.11 that is causing this! Upgrading my Python 2.7 to Bokeh 0.11 also shows the slowdown. I was unable to test Bokeh 0.10 on Python 3.5 since it's not compatible, but 0.11 seems to be the culprit.

**Comment by canavandl** [comment]
What OS/browser are you using?

**Comment by bryevdv** [comment]
> It is within a loop that runs a few thousand times, and it does seem like the plotting becomes slower the more iterations through the loop, so I'm thinking it could be some sort of leak.

In order to support the much simpler to create data apps, we automatically keep track of changes to the current document, so that incremental patches can be accumulated . This is intentional. But if you need to run the same sort of code thousands of times, you'll probably have to manage the current document explicitly. @havocp what is the easiest way to "clear" things to test this theory out? `curdoc().clear()` ?

**Comment by guillochon** [comment]
@canavandl The speed issue is in generating the plots, not displaying them, I'm producing HTML via `file_html` and then saving those files to a directory. The server that's running the Python script is on CentOS 6.

@bryevdv It's also slow at the beginning of the loop too, it just seems to get *slower* as the loop runs more iterations.

**Comment by bryevdv** [comment]
@guillochon can you provide with `cProfile` or another profiling tool?

**Comment by guillochon** [comment]
@bryevdv Sure, I haven't done much profiling myself, could you recommend some settings  for `cProfile` so I can produce an output that's useful to you?

**Comment by bryevdv** [comment]
I usually just start with the default output from `python -m cProfile foo.py`

**Comment by guillochon** [comment]
OK, here's a run of the code limited to 100 loops with Bokeh 0.10: http://pastebin.com/raw/ku4eC9dL

And here's with Bokeh 0.11: http://pastebin.com/raw/9VdCdMb6

Execution time with 0.10: 8.5 seconds, with 0.11: 188.5 seconds.

What sticks out to me in the 0.11 run are these lines in the profile, which I don't see in the 0.10 run:

               ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    12360706/10314044    5.985    0.000   39.262    0.000 encoder.py:288(_iterencode_list)
    44147488/10315682   21.742    0.000   46.806    0.000 encoder.py:341(_iterencode_dict)
    16326538/10315682    7.813    0.000   50.547    0.000 encoder.py:417(_iterencode)

**Comment by bryevdv** [comment]
OK, I can't look at this much in detail until I get back from travel in a few days. If it's possible to make a self-contained runnable example that we could use to start from that would be extremely helpful. In the mean time the only suggestion I have is to try using `Figure` (capital `F`) instead of `figure` and then explicitly doing `curdoc().add_root℗` only at the very last, before output the file.

**Comment by guillochon** [comment]
I changed the `figure` call to `Figure`, and that fixed it! Why the heck is there such a dramatic difference in speed? And why was 0.10 so much faster using `figure`?

**Comment by guillochon** [comment]
Also, all the docs use `figure` in their examples. Should one just replace `figure` with `Figure` everywhere?

**Comment by bryevdv** [comment]
`figure` automatically and adds creates and adds a `Figure` to the current document. That's often fine, but not always, as can be seen here. As mentioned, we added the ability to get change events on any model/property change in the current document (this is to support new Bokeh server apps). Doing it the way I have suggested defers all those events from happening until they are necessary.

**Comment by bryevdv** [comment]
We are still debating what the general guidance should be, and whether any API or behavior changes need to be made. Like I said, it's often perfectly fine to just use `figure` so it may be a documentation issue at the end of the day.

**Comment by bryevdv** [comment]
ping @bokeh/core for thoughts

**Comment by havocp** [comment]
It looks like if a model is part of the doc while you modify it, it triggers a bunch of json encoding?
I'd step 1 figure out exactly why it does that (need a profile with call graph), and then step 2 we could figure out how to avoid it when there aren't any listeners who actually care about the json.

**Comment by mlyons-tcc** [comment]
I stumbled upon this because I noticed running the high level Scatter in Jupyter notebooks is pretty slow to start with (seems slower than running plotting.scatter or plotting.circles which makes me think bokeh isn't handling DataFrames effectively), but becomes increasingly slower as I execute a cell over and over.

I'll be replacing the high level Scatter with low level calls since the high-level seems to have performance issues, and I'll try out using Figure instead before downgrading.

I have been disappointed so far that it seems that Bokeh is actually slower than matplotlib in Jupyter notebooks despite part of the allure being speed on very large or streaming datasets. Maybe I'm not jumping through the right hoops...

**Comment by havocp** [comment]
It would be good to skip the json encode on change events if there are no listeners.

@mlyons-tcc if you are able to determine that your issue is the same as the original issue here please let us know. (it is the same issue if adding your model to the document only when you're done changing it fixes performance. note that lowercase figure() and a few other convenience functions auto-add a model to the document. you can determine if a model is in the document by asking `model.document is not None`)

another pitfall with the auto-add is that you can end up with a bunch of copies of your model in the document, if you write code a certain way. One way to see this happening would be if your document.to_json_string keeps getting larger.

I wouldn't recommend replacing high-level with low-level calls; while that may work it would be "by accident," i.e. the issue is not AFAIK that the high-level calls are inherently slow, more like they could happen to trigger a slow scenario. My suggestion would be to first figure out what pathological thing is happening, like tons of change events caused by modifying an already-in-document model repeatedly, or ever-growing document caused by recreating models without removing the old ones, or whatever it is. These scenarios should be fixable while still using the high-level API.

**Comment by bryevdv** [comment]
> I have been disappointed so far that it seems that Bokeh is actually slower than matplotlib in Jupyter notebooks despite part of the allure being speed on very large or streaming datasets. Maybe I'm not jumping through the right hoops...

These claims are mostly in regards to capabilities of the Bokeh server (which enables users to do downsampling, or can stream data) or the associated `bokeh/DataShader` project which can ne used on certain kinds of data sets up to 100s of millions or billions of points (see the webinar tomorrow).

Can yo be much more specific about what you are trying to do in the notebook that is slower than matplotlib? I am aware of some hot spots that we intend to optimize as time and resources permit, but apart from those I find the performance in the notebook to be quite good. As a baseline, can you reproduce this:

https://github.com/bokeh/bokeh/blob/master/examples/howto/notebook_comms/Continuous%20Updating.ipynb

with matplotlib?

**Comment by mlyons-tcc** [comment]
@bryevdv I'm not sure I understand what you want reproduced in matplotlib with regards to a continuous updating notebook that you pointed out. I think it demonstrates how to work around the problem I have, but it would require abandoning the high level API. I also find it odd to define a plot in a cell prior to the code that is creating it; It doesn't read well so it's counter-productive from a notebook perspective IMO.

I didn't look hard, but I didn't see any performance tests in the repo. Can you point me to some performance numbers compared against matplotlib and other projects if you have them?

All I'm doing is generating a scatter plot of about 3k points. I attached a notebook that demonstrates the performance problem I'm having using bokeh in jupyter notebooks. Right off the bat, bokeh is slower than mpl. On my macbook pro, mpl takes less than a second where bokeh is more than a second. mpld3 and running mpl with the notebook option are quite slow if memory serves correct so I could chalk that up as a win for bokeh since I get all the tools for resize, pan, zoom which is awesome.

What happens next is that I often run the same notebook cells over and over as I iterate on finding a solution or looking at multiple data sets (I'm currently dealing with 100s of thousands of points). @havocp pointed me in the right direction. I got bokeh.io.curdoc(), and I found that the to_json_string() gets larger each time I re-execute the cell. When executing the cell and recreating the plot, it runs slower every execution.
<img width="664" alt="screen shot 2016-02-08 at 11 28 46 pm" src="https://cloud.githubusercontent.com/assets/11726773/12908480/b56d3f5c-cebd-11e5-86ea-b8071381bdb8.png">

How do I make sure the old chart/plot/figure (these terms seem to be interchangeable in bokeh) is removed from the document when I re-execute the cell? This seems like something bokeh should automatically handle in the Jupyter notebook but isn't. Correct me if I'm wrong.

[Bokeh Slower than MPL.ipynb.zip](https://github.com/bokeh/bokeh/files/122633/Bokeh.Slower.than.MPL.ipynb.zip)

**Comment by havocp** [comment]
To clear out the old plot, if you don't care about anything in the document you can `curdoc().clear()`, if you do care about some stuff you could for example name your model and remove it `p.name = "foo"` and `old = curdoc().get_model_by_name("foo")` `if old is not None: curdoc().remove_root(old)` , something like that.

It looks like in 0.11.1 you can also prevent adding stuff to curdoc automatically, https://github.com/bokeh/bokeh/pull/3736 added this, I think it's like `curstate().autoadd=False` up at the top of the notebook.
That may avoid the need for the removal/clear dance. Does not work in 0.11.0 though.

**Comment by bryevdv** [comment]
> @bryevdv I'm not sure I understand what you want reproduced in matplotlib with regards to a continuous updating notebook that you pointed out. I think it demonstrates how to work around the problem I have, but it would require abandoning the high level API. 

You made a general and unqualified claim about "slowness" and I was providing a counterexample. I think we have perhaps not communicated well about the various APIs. The `bokeh.plotting` API is not "low level" in fact it's the one I personally use the most. The charts API is really geared toward statistical slicing and dicing of tabular data (which is why it relies on a data frame), e.g. auto coloring, aggregating and faceting. If the is is not your use case, `bokeh.plotting` is probably better for your needs.

Re: colormaps, you can create and colormap using any color map you like.  

> I didn't look hard, but I didn't see any performance tests in the repo. 

We have discussed and are interested in reporting performance benchmarks, especially for the Bokeh server. We are a small team with a lot of GH issues. If you'd care to help contribute some benchmarking tests, it would certainly be appreciated. 

> Can you point me to some performance numbers compared against matplotlib and other projects if you have them?

Bokeh performance is intimately tied to the performance of the underlying browser canvas implementation. It's not "Bokeh vs MPL" it's
```
 Bokeh on (FF, Chrome, Safari, Edge, ...) * (win, linux, OS X)  * (versions) * (webgl?)

 "vs"  MPL
```
I think it's difficult (impossible) to make the simple comparison you seem to be asking for. 


Regarding your specific notebook:

It's 30k points. MPL has the luxury of rasterizing a single image using numpy in one go and then splatting that one image, all of which is very fast. Bokeh has to serialize all the data, and ship it to an entirely different JavaScript runtime to be deserialized and processed on the HTML5 canvas. This enables lots of new an interesting possibilities, but it is not without trade-offs. 30k is getting into the range where Bokeh may simply not perform as well as other tools on some cases. There are things that might mitigate this: WebGL (where it is supported), a binary array protocol (when we have the person-power to add it), and DataShader (you can check that out right now). 

Otherwise, perhaps "bare" Bokeh is not the right tool for your particular situation. There are always trade-offs, and there are particular use-cases we target. Bokeh cannot satisfy every possible use-case equally well (unless equally badly). The ipython notebook is an important use-case for us, but it is not the most important for instance. Being able to publish a web-based, interactive, streaming, OHLC chart with MACD indicators in < 100 LOC (including the synthetic simulation!) *is* very much important to us.

**Comment by bryevdv** [comment]
Edit: 

In fact, on a mere 3k points, Bokeh is actually *faster*:
```
start = time()
p = figure()
p.circle(df['x'], df['y'], color='navy')
show(p)
stop = time()
print('Bokeh time: %f' % (stop - start))
```
finishes in 0.2 seconds on my machine. Again, specifics matter.

**Comment by bryevdv** [comment]
@bokeh/core all that said, the `autoad` policy needs attention soon. Concrete suggestions welcome.

**Comment by mlyons-tcc** [comment]
Sorry I feel like I hijacked this issue post. Thank you both for pointing me in the right direction, and I think bokeh is a cool tool. Some responses below.

> You made a general claim about "slowness" and I was providing a counterexample.

I didn't mean to provoke defensiveness but provide my experience with using bokeh with Jupyter. I said that I was disappointed that it seems that bokeh is slower when specifically used in Jupyter notebooks (not a general claim). You seem to have answered why matplotlib should be expected to be faster.

Continuous updating is a cool thing, but I by no means would ever consider that a baseline for performance in a Jupyter notebook. I was impressed with some of the demonstrations of the updating plots on web pages but that's not my use case.

> It's 30k points. [Edit: just to clarify, you said 3k, Bokeh is perfectly fast on 3k points in comparison]

Typo. I meant 30k. 30k is a small sized dataset for the plots I'm currently trying to migrate to Bokeh. 200k points would be typical, and 2M is my large dataset plots. I scaled up the amount of data in the example I showed, and it looks like the performance difference becomes even worse. At 330k points, bokeh was 4x slower. At 3.3M points, bokeh crashed the notebook; same problem I had with mpld3. webgl=True did not seem to make a difference in speed, but it's possible I didn't invoke it correctly.

For me, things that take less than a second to execute are inconsequential in a notebook. My concern is when my plot takes several seconds to render. 12 seconds to render with matplotlib vs 48 seconds to render with bokeh is a big deal to me. The data shader looks promising. It was unclear to me whether it works with patches or not. I guess I was hoping that some of that capability was already baked in; my time isn't well spent making visualizations.

> I think we have perhaps not communicated well about the various APIs. The bokeh.plotting API is not "low level" in fact it's the one I personally use the most.

The documentation uses the term "Making High-level Charts" which is what I was basing high-level API. I referred to anything other than that as "low-level".
http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html

**Comment by bryevdv** [comment]
>  I meant 30k. 30k is a small sized dataset for the plots I'm currently trying to migrate to Bokeh. 200k points would be typical, and 2M is my large dataset plots. I scaled up the amount of data in the example I showed, and it looks like the performance difference becomes even worse. At 330k points, bokeh was 4x slower. At 3.3M points, bokeh crashed the notebook; same problem I had with mpld3. webgl=True did not seem to make a difference in speed, but it's possible I didn't invoke it correctly.

At this point you are well outside of Bokeh's basic capabilities. As mentioned, the fundamental architectures between it and MPL are very different, because they have different priorities. To plot 3.3M points in Bokeh involves serializing all 3.3M (times two or there or more) floats into JSON, sending that into a browser, deserializing them in the browser and then rendering them. As you can imagine and imagine and have experienced, that has a very different scaling behavior. To get around it, you have to do something like:

* decimation / downsampling
* pre-rasterization outside the browser

The former you can do with a Bokeh app in a Bokeh server. The latter is what DataShader does automatically when it can. 

I will note that with say, a 1000x1000 canvas, 3.3M points is three times as many pixels as are available to plot onto, and as a  result, just "sending all the data" as-is is probably not going to yield an effective visualization in any case. This problem of perceptual efficacy in dramatically over-plotted situations is another aspect to DataShader.

**Comment by amustafa** [comment]
Hey guys, I know I'm pretty late jumping in on this but I just started using Bokeh. I'm experiencing the same thing as @guillochon. I'm generating 10 static plots, getting the components and embedding them in an html doc. With 11.1,  it's been taking 8-12 seconds running on localhost. When I switched to 10.0, it dropped to 1.5 seconds. I don't have all the details because I'm kind of on a deadline at the moment, but almost all the time with 11.1 was spent in the "components" function. When I switch, the components function is negligible.

**Comment by bryevdv** [comment]
Can you try `reset_output` as a temporary workaround in between plot creations?

**Comment by bryevdv** [comment]
There's a good chance some of this autoadd problem is resolved by he layout work currently underway, but we have to let that settle and bake out first.

**Comment by jonashaag** [comment]
I just hit this, or maybe a related issue. I'm plotting a 10-row Pandas dataset:

```
c_over_time = bokeh.charts.TimeSeries(c10, x='insert_ts', y='amount')
bokeh.charts.show(c_over_time)
```

Takes 12 seconds. Profile: https://gist.github.com/jonashaag/e67a91cf468b6fc77926eaca30e91f70

**Comment by bryevdv** [comment]
Can you provide a complete example to test with?

**Comment by jonashaag** [comment]
What the hell. I put the code in a new notebook and it works fine. Old notebook is still slow. Restarted Jupyter and now it's fast again. 😕

**Comment by rothnic** [comment]
@jonashaag: one possibility is some regression in the handling of the dataframe in charts. So you could try a simple scatter through plotting and see if the slowing comes up again.

**Comment by birdsarah** [comment]
Some updates on performance:

1 - the auto-adding things to document is gone and so there should no longer be a difference between figure and Figure
2 - we have a dramatic notebook speed-up PR about to hit master which should improve the case where you have lots of plots in a notebook or running the same plot over and over again (so if you found that restarting the kernel and refreshing the page gave you a speed-up; or that the more plots you had the slower things got - that issue is now solved).

**Comment by birdsarah** [comment]
Unless there's more concrete steps to take from this issue I think we should close it and open more specific issues.

**Comment by bryevdv** [comment]
I'd like to check this against `0.12` but there was never a complete runnable example provided to reproduce. @guillochon @amustafa @jonashaag can one of you comment re: `0.12` and provide a test script to reproduce is the issue is still present?

**Comment by guillochon** [comment]
@bryevdv I'm intending to upgrade my local install to 0.12 soon and test it out (particularly to take advantage of new responsive stuff), I'll let you know if things are still OK in the new version. For the record changing things to `Figure` in 0.11 had fixed everything for me speed-wise.

**Comment by guillochon** [comment]
@bryevdv I verify that the speed still seems OK in 0.12, although there are now layout issues which I'm going to open separately.

**Comment by bryevdv** [comment]
@guillochon OK great! I am going to go ahead an close this discussion. There are other issues and an epic for making a comprehensive survey of performance improvements.

**Comment by ibmua** [comment]
I'm getting htmls with charts (charts / Area) of some 15000 points getting rendered in a little under 2 minutes on Chrome / Ubuntu on an i7-4960X (with NVidia Maxwell Titan X if that matters). 1700*1200 canvas resolution, but that doesn't seem to make a difference anyway. Is this actually considered normal for Bokeh?

**Comment by bryevdv** [comment]
@ibmua this is a very old issue, it's questionable whether anything here is related to anything current. In any case wrt to Bokeh performance, the answer is "there are very any variables, so it depends" and "therefore we need much more information (versions, platforms, example code....)" the best place to start with a question like this is the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

If it is determined that there is some actual problem, rather then just a general support question, we would then ask for a new issue.

**Comment by ibmua** [comment]
Okay, joined this guy's discussion https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/hVZi6G8yO2k - who seems to have the same experience - and send html.

**Comment by BadrulAlom** [comment]
I was finding my histogram was extremely slow due to not specifying the number of bins and here being large outliers in my data. Sped up considerably when I specified the bins. If you are finding a chart slow perhaps double check the documentation to see if there's any parameters you can set to help it render quicker.
