### ISSUE TITLE
Unable to edit dataTable cell

### ISSUE THREAD

**Issue by ongietorri** [bokeh/bokeh#7891]
I'm using Bokeh 0.12.15 (latest) and after I modify a DataTable cell, I can't save the update. The only thing I can do is focus to the cell and press escape, otherwise the whole DataTable looses focus and is not selectable nor editable.

Is this a regression?

Minimal example:

```
df = pd.DataFrame([[0, 1,2],[1,4,5], [0,5,6]])
df.columns = ['x', 'one', 'two']
cds = ColumnDataSource(df)

columns = [
        TableColumn(field="one", title="ONE", editor=IntEditor()),
        TableColumn(field="two", title="TWO")
    ]

dt = DataTable(source=cds, columns=columns, 
               sortable=True, editable=True, fit_columns=True, selectable=True)

show(dt)
```
![image](https://user-images.githubusercontent.com/5689266/39916018-b920705e-5509-11e8-9bdf-b8557f89e87d.png)

It's the same behavior whether using a notebook or not.

Also, it seems the IntEditor has no effect whatsoever.

Thanks

**Comment by bryevdv** [comment]
This is a duplicate of https://github.com/bokeh/bokeh/issues/7736

**Comment by ongietorri** [comment]
@bryevdv I tried it in 0.12.16 and now the datatable is not editable anymore, even when `editable=True`.

**Comment by bryevdv** [comment]
@ongietorri please provide a complete script that we can run as-is and we will investigate.

**Comment by ongietorri** [comment]
hello @bryevdv, the code provided in this ticket can be used as is.

```
from bokeh.models.widgets.tables import DataTable, IntEditor
from bokeh.models import ColumnDataSource, TableColumn
from bokeh.plotting import output_notebook, show

import pandas as pd

import bokeh
print bokeh.__version__

output_notebook()

df = pd.DataFrame([[0, 1,2],[1,4,5], [0,5,6]])
df.columns = ['x', 'one', 'two']
cds = ColumnDataSource(df)

columns = [
        TableColumn(field="one", title="ONE", editor=IntEditor()),
        TableColumn(field="two", title="TWO")
    ]

dt = DataTable(source=cds, columns=columns, 
               sortable=True,
               editable=True, 
               selectable=True)

show(dt)
```
![image](https://user-images.githubusercontent.com/5689266/40068160-409886dc-5868-11e8-8bcb-62ba7a465488.png)

The result is the same with a bokeh server.

Thanks

**Comment by bryevdv** [comment]
@ongietorri the original code in the ticket did not have imports. There are many tens (hundreds?) of thousands of users, in the interests of fairness on the handful of core developers we must insist on *complete* code samples. With complete code I can confirm a bug. I am currently traveling for a family medical situation, but will look at it when I am able. 

@mattpap any ideas what's going on her? I thought we fixed this.

**Comment by mattpap** [comment]
The regression happened in PR #7818. Reverting it helps, though there are still some unrecoverable stylistic issues after editing. With that PR applied, strange things happen. Double click event, which is responsible for enabling edit mode, is not routed correctly, if at all, thus there is no way to have an editor initialized. It seems that the way slickgrid sets up click and double click events with jquery, shouldn't work reliably in general, I replaced that code with hammerjs. With event routing fixed, editable mode still doesn't work, because as soon as editor is created, slickgrid returns to display mode. This is because it thinks that the active cell changed, but it didn't. At this point I don't know what's the underlying cause.

**Comment by bryevdv** [comment]
Fixed for 0.13

**Comment by zanapepaj** [comment]
For testing purposes (client request) I need to work on windows. I guess the latest upgrade hasn't been implemented in windows yet.

**Comment by bryevdv** [comment]
@zanapepaj I don't really understand what you are saying specifically. Are you saying things work on other plaforms, but don't work on windows? If that's the case, what versions (of bokeh, browser, and windows). Also if that's the case, it would be more helpful for you to make a new issue (with all that information, and a test script to reproduce the problem) so that we can tag it appropriately as windows-specific.

**Comment by zanapepaj** [comment]
Sorry, I wasn't too descriptive in the message above. I tried to install the latest version 0.13.0 by running: 
conda install bokeh
Still getting only version 0.12.16. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/9005900/44395104-2064dc80-a539-11e8-9539-e8799bf687be.png)
