### ISSUE TITLE
[BUG] Exporting Google Maps pngs sometimes not working properly

### ISSUE THREAD

**Issue by michael-yang2** [bokeh/bokeh#9185]
Python: 3.5.2
Bokeh 1.3.4
Selenium 3.3
Ubuntu 16.04

About 50% of the time, trying to export a Google Maps Plot as a png results in the following warnings: 
WARNING:bokeh.io.export:There were browser warnings and/or errors that may have affected your export
WARNING:bokeh.io.export:This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.
  Mh (https://maps.googleapis.com/maps/api/js?key=/*MY API KEY*/&callback=_bokeh_gmaps_callback:126)

The link provided leads to the following line: Google Maps Platform rejected your request. Invalid request. Invalid 'callback' parameter.

```
    output_file(file_name+".html")
    map_options = GMapOptions(lat=initial_coords[0], lng=initial_coords[1], map_type="satellite", scale_control = False,zoom=zoom,tilt=0)
    p = gmap(key,map_options)
    if not os.path.exists('dump'):
        os.makedirs('dump')
    if not os.path.exists('dump/'+file_name+".png"):
        export_png(p,filename="dump/"+file_name+".png", height = int(yres), width = int(xres),timeout = 20)#wait for image to finish generating
    return "dump/"+file_name+".png"

```
About half of the time, the warnings do not show up and I get the plot that I'm looking for. The other half, I end up with a blank, transparent image.

**Comment by mattpap** [comment]
> WARNING:bokeh.io.export:This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.

This was fixed in a recent PR #9168. We now don't touch built-ins needlessly and use a better polyfill when necessary.

**Comment by michael-yang2** [comment]
Great, thanks. Just out of curiosity, do you know what was causing the issue, and why some times it worked fine?

**Comment by bryevdv** [comment]
@mattpap is the issue with the polyfill that is fixed in #9168 actually the root cause of the problem here? Offhand I would have assumed that it is because GMaps render asynchronously (unlike almost all other glyphs) and that sometimes they have not finished rendering before the export starts.

**Comment by mattpap** [comment]
I think this is the root cause, however, even with PR #9168 applies, gmaps still complain. I will have to investigate this. When using the ES6 bundle, which doesn't use polyfills, the problem goes away, though `export_png()` still fails but for a different reason. The problem with signaling when render is fully done was fixed at some point, so `export_png()` should wait until gmaps and all request tiles are loaded.

**Comment by mattpap** [comment]
Actually, this is a bug in GMap API (https://issuetracker.google.com/issues/138963477, the issue is about different a function, but the root cause is the same). For now we will have to pin gmaps to `v=3.36`. `3.37` is the first broken version.

**Comment by mattpap** [comment]
Maybe there is also a better polyfill for `Array.from()` or we will need to enable more polyfills (e.g. `Symbol`, iterators, etc.).
