### ISSUE TITLE
Linked selection tool

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#966]
When I am using a select tool in two linked plots, it is annoying that turning on select in plot1 doesn't turn it on plot2.

**Comment by jakirkham** [comment]
Maybe, I am not understanding the OP, but can't this be trivially solved by follow the linked brushing example here ( http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#id3 ).

**Comment by bryevdv** [comment]
tools for multiple plots can be aggregated into a single toolbar in even more cases now, and in the case of independent toolbars is also possible to programmatically initialize desired tools to be active. Finally if these still don't cover the use-case, a bokeh custom model could be made to do this. I don't think there is any reason to add more complexity to the core library at this point.
