### ISSUE TITLE
[BUG] Impossible to change FactorRange to a lower dimension with different number of factors

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9879]
Initially reported at https://discourse.bokeh.org/t/y-ticks-y-range-error-while-changing-from-2-dimensional-x-range-factors-to-1-dimensional/5106

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.0.1

#### Description of expected behavior and the observed behavior
It should be possible to switch between `factors` of a `FactorRange` without any issues.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import show
from bokeh.layouts import column
from bokeh.models import Button, CustomJS, ColumnDataSource, FactorRange
from bokeh.plotting import figure

fig = figure(x_range=FactorRange(factors=[('a', 'b'), ('b', 'c')]))

ds = ColumnDataSource(data=dict(x=[['a', 'b'], ['b', 'c']], y=[1, 2]))
fig.vbar(x='x', top='y', source=ds)

b = Button(label="Switch to single level")

b.js_on_click(CustomJS(args=dict(fig=fig, ds=ds),
                       code="""\
                           fig.x_range.factors = ['a'];
                           ds.data = {x: ['a'], y: [1]};
                           ds.change.emit();
                       """))

show(column(b, fig))
```

At least one of the causes is that `FactorRange.tops` is not updated if we switch to 1D factors from 2D or 3D factors: https://github.com/bokeh/bokeh/blob/cd74b12ed245c3d53c8bf21420de0f14979aebd0/bokehjs/src/lib/models/ranges/factor_range.ts#L240
There seems to be at least one other issue because the error that you see may depend on the order of the instructions within the `CustomJS.code` above. Seems like a race condition.

**Comment by mattpap** [comment]
> At least one of the causes is that `FactorRange.tops` (...)

And also `mids`. In general the state is not reset fully.

> ```ts
> fig.x_range.factors = ['a'];
> ds.data = {x: ['a'], y: [1]};
> ```

The first line triggers a series of events that will lead to bokehjs using old, incompatible data, before new data is set. It works if you rearrange the lines, which it seems to me to be a fluke (I think it should fail). In general bokehjs isn't well set up for compound changes like this. I suppose it's a joy of reactive programming, but really is a side effect of treating each update individually and relying on chains of events, instead of having a well defined update process.

**Comment by mattpap** [comment]
Also this works:
```ts
try {fig.x_range.factors = ['a'];} catch (e) {};
ds.data = {x: ['a'], y: [1]};
```
However using `setv({factors: ...}, {silent: true})` will fail.

**Comment by mattpap** [comment]
> ```ts
> ds.change.emit();
> ```

This line isn't needed in this context, because you update a property's value. It would be necessary if you modified a part of a value. This way bokehjs' wouldn't be able to detect change.

**Comment by p-himik** [comment]
> I suppose it's a joy of reactive programming, but really is a side effect of treating each update individually and relying on chains of events, instead of having a well defined update process.

I have thought about it before, only in the context of server-client communication. E.g. even something like `plot.x_range.update(start=1, end=2)` sends two patches instead of one.

It seems to me that in both Bokeh and BokehJS it could be possible to accumulate and combine patches and emitted signals and take action only when the execution reaches the event loop (not sure what the analog in JS is called). 
How do you think - would it make sense to try something like that?

**Comment by mattpap** [comment]
> `plot.x_range.update(start=1, end=2)` sends two patches instead of one.

This is an orthogonal issue, but something we intend to fix soon. Well, definitively in 3.0, maybe in 2.x if a fix won't result in changed semantics anyware in bokeh or bokehjs. If you want to take a stab at it then go ahead, otherwise I will fix this sometime later this month.

**Comment by p-himik** [comment]
Yeah, I understand. A better example would probably be something like
```python
plot.x_range.start = 0
plot.y_range.start = 0
```
So it's not a question of making a single function call result in a single patch but rather or making any amount of simultaneous (from the POV of the event loop) changes appear as a single change to the client.

**Comment by mattpap** [comment]
In bokeh this:
```py
plot.x_range.update(start=1, end=2)
```
and in bokehjs:
```ts
plot.x_range.setv({start: 1, end: 2})
```
are equivalent to:
```ts
plot.x_range.start = 0
plot.y_range.start = 0
```
when it comes to client-server updates (signals/events are a separate concern). If you look at the implementation, you will see a simple for loop distributing over changed properties in both cases. Those for loops need to be folded to allow pushing multiple changes in one protocol-level change event.

Additionally it would be nice to allow to synchronize a block of code like this:
```ts
plot.x_range.start = 0
plot.y_range.start = 0
```
so that one isn't forced to use `setv()` or `update()`. I already implemented this locally and it will be part of bokeh 3.0. In bokehjs one will write:
```ts
plot.synchronized(() => {
  plot.x_range.start = 0
  plot.y_range.start = 0
})
```
and in bokeh there will be a context manager (as a substitute for multiline lambdas).

**Comment by bryevdv** [comment]
`hold` and `unhold` already exist on the Python side and can either accumulate or merge changes. There is not a context manager, but could be one, easily.

**Comment by p-himik** [comment]
> `hold` and `unhold` already exist on the Python side

But they just prevent the events from being sent too early - they don't actually combine multiple patches into a single one. At least, I didn't see it in the code.

**Comment by bryevdv** [comment]
Yes, I mean that we should take existing APIs and improve them. Especially since `Document` is the correct place for these kind of synchronizations, not `Plot` (there may not be a plot at all, or changes that span multiple Plots). AFAICT there is an obvious place for `unhold` to generate a single protocol message instead of looping at the end.

**Comment by Higem11** [comment]
It marked as "fixed", but example code still throws out the same error on the 1st click. On the 2nd it does what it should do, but still throwing out an error.

**Comment by p-himik** [comment]
It seems to work if I rearrange the callback code lines:
```js
ds.data = {x: ['a'], y: [1]};
fig.x_range.factors = ['a'];
```
@mattpap Would you say that this is how it's supposed to be done and that the issue can be closed again? Or is there something else that needs to be done in BokehJS?

**Comment by mattpap** [comment]
^^^ this order is what we test in integration tests. However, ultimately both orders should work, assuming this code is run as a synchronized (wrt. signals) block (ref https://github.com/bokeh/bokeh/issues/9879#issuecomment-609430539). I suppose a new issue is in order, because this is a fundamental issue with bokehjs' design, though nicely visualised with this code.

**Comment by Higem11** [comment]
Hmm, and my initial example (link - https://pastebin.com/3wMFknmY) works fine without reordering these lines. Just as it was written originally.
